import express, { type Request, type Response } from "express";
import fs from "fs";
import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";

type StoreSpec = {
  collection: string;
  filename: string;
};

const storeSpecs = {
  brands: { collection: "brands", filename: "brand-configs.json" },
  platformConnections: { collection: "connections", filename: "platform-connections.json" },
  aiWorkflowRules: { collection: "rules", filename: "ai-workflow-rules.json" },
  importedRows: { collection: "rows", filename: "imported-performance-rows.json" },
  workflowTasks: { collection: "tasks", filename: "workflow-tasks.json" },
} satisfies Record<string, StoreSpec>;

type StoreOptions = {
  appDataDir: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function collectionFromInput(input: unknown, collection: string): unknown[] {
  if (Array.isArray(input)) {
    return input;
  }
  if (isRecord(input) && Array.isArray(input[collection])) {
    return input[collection];
  }
  return [];
}

function normalizeCollectionItems(items: unknown[]) {
  return items.filter(isRecord).map((item, index) => ({
    ...item,
    id: readString(item.id) || `item_${Date.now()}_${index}`,
  }));
}

function buildBrandId(input: Record<string, unknown>) {
  const source = [input.companyName, input.brandName, input.platform]
    .map(readString)
    .filter(Boolean)
    .join("-");
  return `brand-${source.replace(/\s+/g, "-") || Date.now()}`;
}

function normalizeBrand(input: unknown) {
  if (!isRecord(input)) {
    return null;
  }

  return {
    id: readString(input.id) || buildBrandId(input),
    companyName: readString(input.companyName) || "待确认公司",
    brandName: readString(input.brandName),
    channelType: readString(input.channelType) || "B2C",
    platform: readString(input.platform),
    owner: readString(input.owner) || "待分配",
    status: readString(input.status) || "待接入",
    integrationMode: readString(input.integrationMode) || "API 预留",
  };
}

function validateBrand(input: unknown, existingBrands: Record<string, unknown>[]) {
  const brand = normalizeBrand(input);
  const errors: string[] = [];
  if (!brand) {
    return { brand: null, errors: ["Brand payload must be an object."] };
  }
  if (!brand.brandName) errors.push("brandName is required.");
  if (!brand.platform) errors.push("platform is required.");
  const duplicate = existingBrands.some(
    (item) =>
      readString(item.companyName) === brand.companyName &&
      readString(item.brandName) === brand.brandName &&
      readString(item.platform) === brand.platform
  );
  if (duplicate) {
    errors.push("Brand already exists for this company and platform.");
  }
  return { brand, errors };
}

function buildMockAIOutput(body: Record<string, unknown>) {
  const rule = isRecord(body.rule) ? body.rule : {};
  const metrics = isRecord(body.structuredMetrics) ? body.structuredMetrics : {};
  const platform = readString(rule.platform) || "global";
  const brandName = readString(rule.brandName) || "unknown brand";
  const workflowType = readString(rule.workflowType) || "sales_drop";
  const rowCount = typeof metrics.rowCount === "number" ? metrics.rowCount : 0;

  return {
    summary: `${platform} / ${brandName} triggered ${workflowType}; ${rowCount} imported rows are available for review.`,
    risk_level: workflowType === "refund_risk" || workflowType === "profit_risk" ? "high" : "medium",
    issue_type: workflowType,
    evidence: [
      {
        metric: "workflow_type",
        value: workflowType,
        explanation: "Generated by the local integrated ops proxy from structured rule context.",
      },
      {
        metric: "row_count",
        value: String(rowCount),
        explanation: "Imported operating rows currently persisted in the JSON ops store.",
      },
    ],
    recommended_actions: [
      {
        title: `Review ${platform} ${brandName} operating exception`,
        action_type: workflowType === "inventory_risk" ? "inventory_check" : "review_followup",
        priority: "medium",
        expected_result: "Confirm whether the recommendation should become a human-owned task.",
      },
    ],
    confidence: 0.72,
    human_review_required: true,
  };
}

export function createOpsIntegrationRouter(options: StoreOptions) {
  const router = express.Router();

  function currentStorePath(spec: StoreSpec) {
    return path.join(options.appDataDir, spec.filename);
  }

  function legacyStorePath(spec: StoreSpec) {
    return path.resolve(process.cwd(), "..", "data", spec.filename);
  }

  async function ensureStore(spec: StoreSpec) {
    const targetPath = currentStorePath(spec);
    try {
      await readFile(targetPath, "utf8");
      return;
    } catch (error) {
      if (!isRecord(error) || error.code !== "ENOENT") {
        throw error;
      }
    }

    await mkdir(path.dirname(targetPath), { recursive: true });
    const legacyPath = legacyStorePath(spec);
    if (fs.existsSync(legacyPath)) {
      const legacyRaw = await readFile(legacyPath, "utf8");
      await writeFile(targetPath, legacyRaw, "utf8");
      return;
    }

    await writeFile(
      targetPath,
      `${JSON.stringify({ updatedAt: new Date().toISOString(), [spec.collection]: [] }, null, 2)}\n`,
      "utf8"
    );
  }

  async function readStore(spec: StoreSpec) {
    await ensureStore(spec);
    const raw = await readFile(currentStorePath(spec), "utf8");
    const parsed = JSON.parse(raw);
    const items = Array.isArray(parsed[spec.collection]) ? parsed[spec.collection] : [];
    return {
      source: "json-file",
      path: currentStorePath(spec),
      updatedAt: readString(parsed.updatedAt) || new Date(0).toISOString(),
      [spec.collection]: normalizeCollectionItems(items),
    };
  }

  async function replaceStore(spec: StoreSpec, input: unknown) {
    const items = normalizeCollectionItems(collectionFromInput(input, spec.collection));
    const nextStore = {
      updatedAt: new Date().toISOString(),
      [spec.collection]: items,
    };
    await mkdir(options.appDataDir, { recursive: true });
    await writeFile(currentStorePath(spec), `${JSON.stringify(nextStore, null, 2)}\n`, "utf8");
    return nextStore;
  }

  function sendError(res: Response, statusCode: number, error: unknown) {
    res.status(statusCode).json({
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }

  router.get("/master-data/brands", async (_req, res) => {
    try {
      res.json({ ok: true, ...(await readStore(storeSpecs.brands)) });
    } catch (error) {
      sendError(res, 500, error);
    }
  });

  router.post("/master-data/brands", async (req, res) => {
    try {
      const store = await readStore(storeSpecs.brands);
      const brands = Array.isArray(store.brands) ? store.brands : [];
      const { brand, errors } = validateBrand(req.body, brands);
      if (!brand || errors.length > 0) {
        return res.status(400).json({ ok: false, error: errors.join(" ") });
      }
      const nextStore = await replaceStore(storeSpecs.brands, { brands: [brand, ...brands] });
      return res.status(201).json({ ok: true, source: "json-file", brand, ...nextStore });
    } catch (error) {
      return sendError(res, 500, error);
    }
  });

  router.get("/config/platform-connections", async (_req, res) => {
    try {
      res.json({ ok: true, ...(await readStore(storeSpecs.platformConnections)) });
    } catch (error) {
      sendError(res, 500, error);
    }
  });

  router.put("/config/platform-connections", async (req, res) => {
    try {
      res.json({ ok: true, source: "json-file", ...(await replaceStore(storeSpecs.platformConnections, req.body)) });
    } catch (error) {
      sendError(res, 400, error);
    }
  });

  router.get("/config/ai-workflow-rules", async (_req, res) => {
    try {
      res.json({ ok: true, ...(await readStore(storeSpecs.aiWorkflowRules)) });
    } catch (error) {
      sendError(res, 500, error);
    }
  });

  router.put("/config/ai-workflow-rules", async (req, res) => {
    try {
      res.json({ ok: true, source: "json-file", ...(await replaceStore(storeSpecs.aiWorkflowRules, req.body)) });
    } catch (error) {
      sendError(res, 400, error);
    }
  });

  router.get("/ops/imported-rows", async (_req, res) => {
    try {
      res.json({ ok: true, ...(await readStore(storeSpecs.importedRows)) });
    } catch (error) {
      sendError(res, 500, error);
    }
  });

  router.put("/ops/imported-rows", async (req, res) => {
    try {
      res.json({ ok: true, source: "json-file", ...(await replaceStore(storeSpecs.importedRows, req.body)) });
    } catch (error) {
      sendError(res, 400, error);
    }
  });

  router.get("/ops/workflow-tasks", async (_req, res) => {
    try {
      res.json({ ok: true, ...(await readStore(storeSpecs.workflowTasks)) });
    } catch (error) {
      sendError(res, 500, error);
    }
  });

  router.put("/ops/workflow-tasks", async (req, res) => {
    try {
      res.json({ ok: true, source: "json-file", ...(await replaceStore(storeSpecs.workflowTasks, req.body)) });
    } catch (error) {
      sendError(res, 400, error);
    }
  });

  router.post("/ai/brand-ops/run", (req: Request, res: Response) => {
    if (!isRecord(req.body) || !isRecord(req.body.rule) || !isRecord(req.body.prompt)) {
      return res.status(400).json({
        ok: false,
        providerMode: "proxy",
        modelName: process.env.AI_PROXY_MODEL_NAME || "server-mock-model-v1",
        rawOutput: null,
        warnings: [],
        error: "rule and prompt are required.",
      });
    }

    if (req.body.humanReviewRequired !== true) {
      return res.status(400).json({
        ok: false,
        providerMode: "proxy",
        modelName: process.env.AI_PROXY_MODEL_NAME || "server-mock-model-v1",
        rawOutput: null,
        warnings: [],
        error: "humanReviewRequired must be true.",
      });
    }

    return res.json({
      ok: true,
      providerMode: "proxy",
      modelName: process.env.AI_PROXY_MODEL_NAME || "server-mock-model-v1",
      rawOutput: buildMockAIOutput(req.body),
      warnings: [
        "Local ops proxy is using mock output. Replace this service with a real model call after prompt/schema governance is stable.",
      ],
    });
  });

  return router;
}
